name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:2021-05-15
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        run: make cookbook.pdf
      - name: 'Upload PDF'
        uses: actions/upload-artifact@v2
        with:
          name: cookbook
          path: build/cookbook.pdf
